name: Build Project

on: [push]

env:
  PROJECT_PATH: 'src/Azox.Core/Azox.Core.csproj'
  
jobs:
  deploy:
    name: Build Project
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set .NET Core 6.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Build Project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release
